### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [tsmcandrew/tea-cozy#4]
Summary: Meets Expectations

Great job on this project, it looks like the spec! The code was very organized and easy to read which is a big plus. The only thing's I pointed out are more of a nit-pick than a big issues visually. To have your code semantically correct, and keeping your code DRY (don't repeat yourself) take a look at the issues. Over all good job, next try to add a menu with pricing , check out themeforest.com for ideas. Great job!

**Comment by tsmcandrew** [comment]
Thanks Mike
